

model_name: ntnet
seed: 1
gpu_id: [0]

network_g:
  img_channel: 3 
  width: 32
  middle_blk_num: 8
  noise_injection_level: 100

  
train:
  lr: !!float 1e-4
  batch_size: 4 
  use_scheduler: False
  max_steps: 100
  ckpt_steps: 10
  num_workers: 4
  spatial_freq_weight: 0.001

dataset:
  gt_path: /home/xteam_zdw/dataset/DIV2K_train_HR
  crop_size: 128 
  noise_type: isp

path:
  ckpt_path: ./ckpt
  model_save_path: ./experiments
  ckpt_resume_path: ~



